### ISSUE TITLE
ping pong

### ISSUE THREAD

**Issue by ilgooz** [ilgooz/aliengame#1]
Hey @fadeev. If you would like to take a look, here is how the game sdk/api is utilized to create a _cli_ app to control the game engine:

https://github.com/ilgooz/aliengame/blob/master/interface/alienctl/cmd/game.go#L35-L67

**Comment by fadeev** [comment]
@ilgooz we'll review your submission very soon. I do appreciate that you've added a proper CLI to this 👍

**Comment by ilgooz** [comment]
I guess this is done :smile:
